name: quiz_app
description: A beautiful Flutter quiz application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  connectivity_plus: ^5.0.2

  flutter_local_notifications: ^17.2.3
  url_launcher: ^6.2.5
  http: ^1.2.1
  uuid: ^4.4.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon/
    - assets/qr.png
    - assets/50.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#7C9CFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"